# Estágio 1: Usar a imagem oficial do Nginx
FROM nginx:alpine

# Copiar a configuração personalizada do Nginx para dentro do contêiner
# (Vamos criar este arquivo no próximo passo)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80, que é a porta padrão do Nginx
EXPOSE 80

# Comando padrão para iniciar o Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]
